### PR TITLE
fix(script): price extraction logic

### LINKED ISSUE #12: Workflow Fail: Extract data from DRTT #2
####  ➡️  Run python `script.py`
```shell
Run python script.py
  python script.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3855845927/jobs/6571353639#step:5:3).11.1/x6[4](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3855845927/jobs/6571353639#step:5:4)

```

### ➡️ Run python `script.py`
```shell
Run python script.py
  python script.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3856013359/jobs/6571714706#step:5:3).11.1/x6[4](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3856013359/jobs/6571714706#step:5:4)

Traceback (most recent call last):
  File "/home/runner/work/devo-abastecer/devo-abastecer/script.py", line [5](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3856013359/jobs/6571714706#step:5:5)[8](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3856013359/jobs/6571714706#step:5:8), in <module>
    price = float(gas_info[i + 1][:-1].replace(',', '.'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Gasolina IO[9](https://github.com/carlosrsabreu/devo-abastecer/actions/runs/3856013359/jobs/6571714706#step:5:9)'
Error: Process completed with exit code 1.
```

## Steps to Reproduce the Problem

>[Extract data from DRTT](https://github.com/carlosrsabreu/devo-abastecer/actions/workflows/main.yml)
1. The issue currently exists in all branches.
2. The issue can be reproduced by running the workflow manually or on schedule.

### PR DESCRIPTION
**Pull request by HarryVasanth**
### What this PR does

Fixes issue #12, that's causing the scheduled workflow to fail.

### Where should the reviewer start

1.  Take a look at Actions ([`workflows`](https://github.com/carlosrsabreu/devo-abastecer/tree/main/.github/workflows)) ➡️  Extract data from DRTT ([`main.yml`](https://github.com/carlosrsabreu/devo-abastecer/blob/main/.github/workflows/main.yml))
2. The workflow fails due to the issue in line [`58`](https://github.com/carlosrsabreu/devo-abastecer/blob/c76027e34a1a076cb403048a49e4bcef2f9b35e4/script.py#L58) of the `script.py` file.

### Related issues
[Extract data from DRTT](https://github.com/carlosrsabreu/devo-abastecer/actions/workflows/main.yml)

Closes #12

### CODE REVIEW

**Review by joaoofreitas — APPROVED** [review]
Looks great to me.

**Comment by joaoofreitas** [comment]
@Dntfreitas 

Can you review the pipeline on GitHub actions?
The _fix_ looks good to me.

Thanks for the contribution @HarryVasanth.

**Review by carlosrsabreu — APPROVED** [review]
@HarryVasanth ,

Thanks for your contribution, first of all!

This looks great to me!

@Dntfreitas as @joaoofreitas said, can you review the GitHub actions so we can merge this PR? 

Thanks to all of you 🙏

**Review by Dntfreitas — APPROVED** [review]

**Comment by Dntfreitas** [comment]
@carlosrsabreu looks good to me. You can merge :)

**Pull request merged**
