### PR TITLE
[FIX]: Issue #17

### LINKED ISSUE #17: [BUG]: Workflow fails on `main.yml`
### **Describe the bug**

1. Currently, the GitHub workflow `main.yml ` is failing.
[Extract data from DRTT](https://github.com/carlosrsabreu/devo-abastecer/actions/workflows/main.yml)

2.  The file `history/img/plot.png` doesn't exist in the repository.
3. However, the workflow is still referring to it and attempts to make a commit:
https://github.com/carlosrsabreu/devo-abastecer/blob/010431a06eb908acff66d6f896f3b8f15e87dff9/.github/workflows/main.yml#L36

### **Expected behaviour**
- The GitHub workflow `main.yml ` executes as usual.

### **To Reproduce**
- Trigger the GitHub workflow: `main.yml`

### **Additional context**
- N/A

### PR DESCRIPTION
**Pull request by HarryVasanth**
### Related issues

Closes #17 

### What does this PR do?

**This PR addresses all the issues mentioned on #17 and is solving the following issues:**
1. Currently, the GitHub workflow `main.yml ` is failing.
[Extract data from DRTT](https://github.com/carlosrsabreu/devo-abastecer/actions/workflows/main.yml)

2.  The file `history/img/plot.png` doesn't exist in the repository.
3. However, the workflow is still referring to it and attempts to make a commit:
https://github.com/carlosrsabreu/devo-abastecer/blob/010431a06eb908acff66d6f896f3b8f15e87dff9/.github/workflows/main.yml#L36

### Solution Overview

- `main.yml`: removed broken commit & refactored
- `history_plot.yml`: refactored
- `script.py`: fixed typo
- `readme`: updated workflow badges

### Implementation Details

This is the quick and clean way 😉

### CODE REVIEW

**Comment by Dntfreitas** [comment]
Sorry about this, @HarryVasanth 

I didn't notice that 😭

**Comment by HarryVasanth** [comment]
Haha, no worries. It happens to all of us, and it's never the PR's fault, but the reviewers.
You could stare 👀 at the reviewer 👉 @joaoofreitas @carlosrsabreu 👈
# 🤣

**Comment by joaoofreitas** [comment]
I'm a rookie at pipelining. 🤣

**Comment by HarryVasanth** [comment]
Maybe in the future we can try these plots:
https://github.com/RainCloudPlots/RainCloudPlots

Also, @Dntfreitas / @carlosrsabreu, I think it'll be better if you enable [Discussions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) on this repo.
Easier to discuss stuff and weigh-in opinions; what do you think?

**Review by carlosrsabreu — APPROVED** [review]
Now it's safe to merge ehehe

Thank you, @HarryVasanth !

**Pull request merged**
